### ISSUE TITLE
Create an ARM VM to compile these in

### ISSUE THREAD

**Issue by virtuald** [robotpy/roborio-packages#10]
It seems like this might not be that hard to do, and would allow us to build things like OpenCV and not have to mess around with the limited resources that the RoboRIO has on it.

**Comment by PeterJohnson** [comment]
Not exactly related, but is the version of OpenCV packaged by NI usable for Python?

**Comment by virtuald** [comment]
Oh neat, that wasn't available last year. Nice.

LOL:

```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for python-opencv:
 *  libopencv-nonfree2.4 (>= 2.4.9+git0+df8e28283f) * 
 * opkg_install_cmd: Cannot install package python-opencv.
```

It uses their packages for python2 and numpy 1.7 (presumably non-accelerated, since there's no corresponding ATLAS/et al dependency).

**Comment by virtuald** [comment]
Looks like the `qemu-system-arm` that I have installed on Fedora 22 supports xilinx-zynq-a9.

**Comment by virtuald** [comment]
I was able to create an appropriate filesystem and create a qcow image from it, but was not able to successfully boot u-boot or a kernel in qemu. I feel like I was close, but I think I've spent enough time trying to get it to work at this point.

**Comment by virtuald** [comment]
I started playing with it a bit more, and got the VM working most of the way, I'll push it into a separate repo.
