### ISSUE TITLE
Remove mjpg-streamer in favor of using robotpy-cscore

### ISSUE THREAD

**Issue by virtuald** [robotpy/roborio-packages#14]
Need to adjust the installer so it can install it.

**Comment by imdunne8** [comment]
After looking over cscore and robotpy-cscore, it would actually be awesome if you guys could just leave mjpg-streamer in this repo as an option.  We used it last year and will again this year as basically the most simple solution for streaming an MJPG stream back to the driver station from a USB camera.  We're a Java team and therefore don't have (or want to have) the whole robotpy implementation running on our roborio, and as of right now it doesn't look like there's a straightforward and quick installation of the base cscore package.  If you really want to get it out of this repo then our team can always fork a previous revision and keep that around, but there might be some other teams out there that come looking for this in the future - I know we weren't the only team using it last year.

**Comment by virtuald** [comment]
Why not use java cscore on the RoboRIO?

**Comment by virtuald** [comment]
I mean, there's nothing you could do simpler than [this](https://github.com/wpilibsuite/EclipsePlugins/blob/master/edu.wpi.first.wpilib.plugins.java/resources/templates/examples/QuickVision/src/org/usfirst/frc/team190/robot/Robot.java):

```
public class Robot extends IterativeRobot {
	@Override
	public void robotInit() {
		CameraServer.getInstance().startAutomaticCapture();
	}

}
```

**Comment by imdunne8** [comment]
Wow, sorry about that... completely didn't realize CameraServer was part of wpilib already and was assuming we'd have to build ourselves.  Thanks for that, should definitely be easy enough.

**Comment by virtuald** [comment]
Removed in 02c3025
