### ISSUE TITLE
Contemplate more automation for this repo

### ISSUE THREAD

**Issue by virtuald** [robotpy/roborio-packages#20]
It's still largely a manual process, and there's not an easy way to stage stuff for testing without wiping out the production repo. One potential solution is using docker + my ODROID C2 as a build slave that auto builds on pushes to master (gitlab-ci actually makes this sort of thing easier).

**Comment by virtuald** [comment]
One thing that would be useful if I used that sort of system is standing up a local squid cache on the opkg feeds (which honestly, I should do anyways).

**Comment by auscompgeek** [comment]
Might be interesting: http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

**Comment by virtuald** [comment]
Hm. Would need a private docker image to make that work.

**Comment by virtuald** [comment]
I've moved all of the python wheel building to the https://github.com/robotpy/roborio-wheels/ project, and robotpy wheels are now cross compiled via github actions. Only a few things are left, I don't think it makes sense to move the rest of them at this time.
