### ISSUE TITLE
Integrate compileall patch

### ISSUE THREAD

**Issue by virtuald** [robotpy/roborio-packages#22]
Patch from https://github.com/python/cpython/pull/4856 needs to be integrated into python package for 2018.

Then update pyfrc: https://github.com/robotpy/pyfrc/issues/90

**Comment by auscompgeek** [comment]
Python 3.6.4 was released a couple of weeks ago with various bugfixes, so might be a good time to get this in and have everyone running an up-to-date Python on their roboRIO.

**Comment by virtuald** [comment]
I will start the build tonight.

**Comment by virtuald** [comment]
I have started said build.

**Comment by virtuald** [comment]
Well, that didn't take nearly as long as I thought it would. Done.
