### ISSUE TITLE
Bitbake error

### ISSUE THREAD

**Issue by burru0** [robotpy/roborio-packages#28]
I'm trying to make the cross-compiling of the library libgfortran on a virtual machine in a windows pc, to later build the library on a linux device. Following the guide I have encountered two problems:

- When I execute the command "git cherry-pick de2aa7a56790581406f219339c9022638cd47494", I get the error "fatal: bad object".

- When I execute "bitbake libgfortran", the following error appears:
```
ERROR: Function failed: do_compile (log file is located at /home/burruzola/nilrt/build/tmp_nilrt_3_0_x64-glibc/work/x86_64-linux/automake-native/1.14.1-r0/temp/log.do_compile.4677)
ERROR: Logfile of failure stored in: /home/burruzola/nilrt/build/tmp_nilrt_3_0_x64-glibc/work/x86_64-linux/automake-native/1.14.1-r0/temp/log.do_compile.4677
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 6
| : && /bin/mkdir -p doc && { PATH='/home/burruzola/nilrt/build/tmp_nilrt_3_0_x64-glibc/work/x86_64-linux/automake-native/1.14.1-r0/build/t/wrap':$PATH && export PATH; } && /usr/bin/perl /home/burruzola/nilrt/build/tmp_nilrt_3_0_x64-glibc/work/x86_64-linux/automake-native/1.14.1-r0/automake-1.14.1/doc/help2man --output=doc/automake-1.14.1 automake-1.14
| help2man: can't get `--help' info from automake-1.14
| Try `--no-discard-stderr' if option outputs to stderr
| Makefile:3707: recipe for target 'doc/automake-1.14.1' failed
| make: *** [doc/automake-1.14.1] Error 255
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile
```
Although a "build" folder is created with a subfolder for the machine inside it, the .ipk files are nowhere to be found as the bitbake command is not fully completed.

**Comment by virtuald** [comment]
What instructions are you following? It would probably just be easier to use our binaries if you're going to run on a roboRIO.

**Comment by burru0** [comment]
I'm following the instructions on the 2016 branch "roborio-packages/atlas_libs/".
When the .ipk files have been built, I plant to install them on a sbRIO device.

**Comment by virtuald** [comment]
Heh, those instructions are pretty old, many of the patches you need are already applied. My most recent set of instructions are on the README for https://github.com/robotpy/roborio-atlas . I think I used those mostly untouched for this year (except different fortran versions). 

Good luck!
