### ISSUE TITLE
os.getgroups() produces segmentation fault

### ISSUE THREAD

**Issue by virtuald** [robotpy/roborio-packages#3]
Trying to execute the os.getgroups function in python produces a segmentation fault.

```
$ python3
>>> import os
>>> os.getgroups()
```

This works OK on my ubuntu desktop running python 3.4.1.

Originally filed by @dangyogi at https://github.com/robotpy/robotpy-wpilib/issues/125

**Comment by dangyogi** [comment]
This is not something I need for the competition, so can be a low priority...

**Comment by virtuald** [comment]
Closing and won't fix, will revisit if this is still an issue in python 3.5 in 2016.
