### ISSUE TITLE
Adding Python 3.5

### ISSUE THREAD

**Issue by computer-whisperer** [robotpy/roborio-packages#7]
If I were to try and add python 3.5 here, what would that involve? Would it be better to add a seperate python35 package, or to upgrade the existing python3?

**Comment by PeterJohnson** [comment]
I think you should just be able to update the existing python3 package.  I don't see a need to make a separate package since it's backwards compatible?

**Comment by computer-whisperer** [comment]
Forgive me if I am missing the obvious, but how are these build scripts supposed to be used? I tried running "make" in "ipkg/python3/" with the result of "No rule to make target 'data', needed by '../python3_3.4.2_armv7a-vfp-neon.ipk'.  Stop."

**Comment by PeterJohnson** [comment]
Run "make ROBORIO=<ip address/DNS name> all" to perform the build.  This runs the full sequence of clean, install-deps, fetch, extract, build, install, getdata, and ipk.  See Mk/ipkg.post.mk for all of the variables that can be set.  This definitely needs to be documented.

**Comment by virtuald** [comment]
Anyone made progress here?

**Comment by computer-whisperer** [comment]
I'm sorry. I had made some progress on this, but got stuck and kinda forgot about it. If someone else wants to take a crack at it, then go ahead.

**Comment by virtuald** [comment]
Well, I updated the files for python 3.5 and numpy and pushed them to a branch, and it's building right now. If I recall correctly from last year, it's an hour or two to compile, so I'm heading to bed. Seems fine so far though.

https://github.com/robotpy/roborio-packages/tree/py35

**Comment by virtuald** [comment]
After some futzing, the build works. Just need to get stuff uploaded to a new opkg repo.

**Comment by virtuald** [comment]
Upgraded my roborio to the 2016 image, looks like they changed architecture name for the packages to `cortexa9-vfpv3`. Uploaded fixes to https://github.com/robotpy/roborio-packages/tree/2016, starting a build tonight and we'll see what happens.

**Comment by virtuald** [comment]
Fixed and uploaded to 2016 feed.
